choojs/hyperx

index.js

When a tag that is written in the 'tagName#id.class' shorthand format (which is accepted by functions such as 'virtual-dom/h') is passed into `selfClosing`, the result is always `false`, even if the tagName itself is a valid self-closing tag.
**Before**
```js
selfClosing('div');               // false
selfClosing('div#thing');         // false
selfClosing('div.thing');         // false
selfClosing('div#thing.thing');   // false
selfClosing('input');             // true
selfClosing('input.thing');       // false *
selfClosing('input#thing');       // false *
selfClosing('input#thing.thing'); // false *
```
\* false negatives
**After**
```js
selfClosing('div');               // false
selfClosing('div#thing');         // false
selfClosing('div.thing');         // false …
```

Updated closeRE regex so that it stops returning false negatives.

---

index.js
test/key.js

In react you can use the [spread] operator like so 
```javascript
<Element {...this.props} />
```
Unfortunately 
```javascript
hx`<Element ${...this.props} />`
```
isn't valid... However I propose
```javascript
hx`<Element ${this.props} />`
```
As no key is given this can be handled in the parse which this pull request handles (hopefully in an ok way)
I have written to tests for this new functionality.
[spread]:https://facebook.github.io/react/docs/jsx-spread.html

Multiple properties support

---

index.js
test/children.js

React complains if children is sent as an empty array instead of undefined.
```javascript
hx`<img href=${href}>`
```
Results in
Warning: img is a void element tag and must not have `children` or use `props.dangerouslySetInnerHTML`. Check the render method of null.
This pull request sends the children array only if there are any and the tests pass.

If no child elements exist call h with undefined instead of []

---

index.js
test/svg.js

This allows SVG support and closes GH-18
I tried using [svg-tags](https://github.com/element-io/svg-tags) but it includes `svg` itself and other tags which caused tests to fail. So I figured it would be better to just copy the needed tags in directly.
Thanks!

Add svg tags to self closing regex

---

index.js

Ref https://github.com/substack/hyperx/pull/19#issuecomment-192161066
I looked into each tag to narrow down the list of tags known to self close. They are my best guess by looking at MDN, the specification and google searches of usage.
I removed the following tags as they are marked deprecated:
```js
'altGlyph', 'altGlyphDef', 'altGlyphItem', 'animateColor',
```
I removed these tags as they are not self closing:
```js
'animateMotion', 'clipPath', 'defs', 'filter', 'font', 'font-face', 'font-face-src',
'foreignObject', 'linearGradient', 'marker', 'mask', 'metadata', 'pattern',
'radialGradient', 'switch', 'symbol', 'textPath', 'tspan',
```
I removed this tag as it appears no browser supports it:
```js
'color-profile',
```

Narrow the list of SVG tags to known self closing ones

---

index.js

Turns out `feMerge` is not self closing:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/feMerge
Related to https://github.com/shama/bel/issues/23#issuecomment-206044732
Thanks!

Remove feMerge from self closing

---

index.js
test/attr.js

Not entirely sure in which case `[ATTR_BREAK],[ATTR_VALUE,reg]` made sense, so I presume it might be a mistake? I base this on not being able to find a path through the "node synthesizer" that fits a `ATTR_BREAK` followed by a `ATTR_VALUE`.

Fix unquoted attributes

---

index.js
test/comment.js

Large views written in hyperx can easily become quite messy, especially with nested expressions. Comments can help clear things up and later be removed in production using tools such as [hyperxify](https://github.com/substack/hyperxify) or [yo-yoify](https://github.com/shama/yo-yoify). Comments are disabled by default so as not to brake any existing implementations, though the result will differ as hyperx currently can't handle comments at all and output gets kind of messed up. With this change comments will simply be excluded unless otherwise specified in the options.
See an example implementation in bel: https://github.com/tornqvist/bel/commit/dc647d5070d6da7b3d73694423ff06d11832cfc4
Before:
```javascript
const { createElement }  = require('bel')
const hyperx = require('hyperx')
const …
```

Add support for comments

---

index.js
test/attr.js

From my understand in the [HTML syntax spec on attributes](https://www.w3.org/TR/html5/syntax.html#attributes-0), a wider range of characters can be supported.
For example in Vue, you have things like `<div @click=...>`, or `<div :href='foo'>`.  I'm building something with similar syntax and uses hyperx.
Edit: It's worth mentioning these don't actually go to the DOM (which would probably make them invalid, over `data-*`).  They are processed down to regular attributes.

Add better character range for attributes

---

index.js
test/key.js

This fixes a bug where the parser doesn't realise that void elements with attributes are closed.
The problem was that the attribute parser code erroneously consumed the `CLOSE` element in the loop in index.js:75. This stopped the special selfClosing logic from running.

Fixed issue #55 parsing void tags

---

index.js

We had edge cases in nested templates where functions and objects were getting concatenated to empty strings resulting in [Object] or function() { ...} appearing in the rendered HTML. Simply checking that the second argument to concat was not going to be the empty string solved the problem. We ran your tape test suite. All tests passed. We were unable to define a simple unit test that reproduced the error we were having, but it has definitely been resolved.

Modified 78, 82 to prevent edge cases of functions and objects converting to strings

---

readme.markdown
test/z_hyperscript.js

Fixes GH-59
This example:
```js
var tree = hx`<div>
<h1 y="ab${1+2}cd">hello ${title}!</h1>
</div>`
console.log(tree.outerHTML)
```
works fine on the server but in the browser, hyperscript ignores the `y=""` attribute. So updating the example and test to use `data-y=""` with a note about why we dont use custom attributes with hyperscript.

Fix readme and test as custom attrs dont work in the browser with hyperscript

---

index.js
test/br.js

Fixes GH-38
Fixes shama/bel#107
Now we can omit the space on a self closing tag as one commonly does with: `<br/>`

Dont break on self closing tags without a space.

---

index.js
test/tags.js

This PR adds the feature to set tags as variables. 
Fixes: #67
Related to: #9 
```js
class Component extends HTMLElement { ... }
const tree = hx`
<${Component} arg1="foo">
<span>child</span>
</${Component}>
`
```

Add support for custom components as variables

---

index.js
readme.markdown
test/fragments.js

This adds `createFragment` to optionally handle multiple root elements.
Closes #65

Add .createFragment option

---

index.js
test/attr.js

Hi! Looks like `null` and `undefined` attribute values don't work right at this moment. They are used as strings "undefined", "null" now.
Related: #27.

Fixed issue #55 undefined attribute values are converted to strings

---

index.js
test/comment.js

Comment state is preserved when entering a template `${embed}` part,
so you can do things like
```js
html`
<div>
${someElementThatIWantShown()}
</div>
`
```
instead of the somewhat clumsy
```js
html`
<div>
${''/*
someElementThatIWantHidden()
*/}
</div>
`
```
Of course, in the first situation, someElementThatIWantHidden() is still evaluated, just not inserted.
With `opts.comments = true`, the embedded parts are stringified and concatenated.

Fix template parts inside comments

---

index.js
test/fragments.js

Previously, this already generated a fragment, with 3 nodes:
```js
hx`
<a></a>
${[1, 2]}
`
```
It would make sense for this to also generate a fragment, with 2 nodes:
```js
hx`
${[1, 2]}
`
```

Treat single top-level array template part as a fragment

---

index.js
package.json
readme.markdown
test/style.js
test/svg.js

fixes:
* https://github.com/choojs/hyperx/issues/41
* https://github.com/choojs/nanohtml/issues/151
This changes causes the tests from https://github.com/choojs/hyperx/pull/52/commits/f1803d5443a83a64d169af542e9124d55f105952 to pass, and they've been included too.

handle optional closing tags for self-closing tags. fixes #41

---

package.json

I temporarily published to my own npm module while waiting for maintainership role.  Accidentally merged that module name into master.

restore npm package name
